export type Stats = Record<string, string | number | null>
export type Trait = { code: string; name: string; description?: string }
export type PassiveSemantics = { status?: string; unit?: string | null; meaning?: string | null; target_kind?: string | null }
export type HeroPassive = { code?: string | null; name?: string | null; description?: string | null; target?: string | null; source_value?: string | number | null; semantics?: PassiveSemantics }
export type Acquisition = { id: string; name: string; kind: string; medalId?: string; current: boolean; evidenceType?: string; status?: string; sourcePath?: string; sourceRecord?: string }
export type SemanticFact = { value: string | number | null; status: 'source_defined' | 'strongly_supported' | 'unresolved'; source_field: string; meaning?: string | null; name?: string }
export type LegacyAvailabilityFact = { value: boolean | null; status: 'legacy_unverified'; source_field: string; source_path: string }
export type StatFact = SemanticFact & { label: string; unit: string }
export type Hero = { id: string; name: string; class?: string; tribe?: string; element?: string; damageType?: string; sex?: string; mobility?: string; portraitUrl?: string; stats: Stats; statSemantics?: Record<string, StatFact>; sourceCalculations?: Record<string, SemanticFact>; traits: Trait[]; passive: HeroPassive; progression: Record<string, string | number | null>; progressionSemantics?: Record<string, SemanticFact>; availability: Record<string, boolean | null>; legacyAvailability?: Record<string, LegacyAvailabilityFact>; acquisition: Acquisition[]; classification: string; variantOf?: string }
export type AttributeFact = { raw_value: string; value: number; display_value: number; status: string; meaning?: string; unit: string; source_attribute: string }
export type SkillPart = { kind: string; attributes: Record<string, string>; attribute_semantics?: Record<string, AttributeFact>; text?: string }
export type Skill = { id: string; name: string; description?: string; descriptionTemplate?: string; descriptionParameters?: Record<string, string>; unresolvedPlaceholders?: string[]; type?: string; components: SkillPart[]; raw?: Record<string, string> }
export type FilterOption = { value: string; label: string }
export type Filters = { classes: string[]; tribes: string[]; elements: string[]; damageTypes: string[]; rarities: string[]; mobilities: string[]; acquisitions: string[]; attributes: FilterOption[] }
export type HeroPage = { items: Hero[]; total: number; page: number; pageSize: number }
export type HeroDetailModel = { hero: Hero; skills: Skill[] }
export type HeroQuery = { search: string; heroClass: string; element: string; rarity: string; mobility: string; acquisition: string; attribute: string }
