import { useCallback, useEffect, useState } from 'react'
import { getHero } from '../api'
import { humanize, skillMechanics } from '../format'
import type { HeroDetailModel } from '../models'
import { navigate } from '../navigation'
import { ErrorState, LoadingState } from './AsyncStates'
import { Portrait } from './Portrait'
import { FormattedText } from './FormattedText'

export function HeroDetail({ id }: { id: string }) {
  const [data, setData] = useState<HeroDetailModel | null>(null), [error, setError] = useState<string>(), [attempt, setAttempt] = useState(0)
  const retry = useCallback(() => setAttempt(value => value + 1), [])
  useEffect(() => { const controller = new AbortController(); setError(undefined); getHero(id, controller.signal).then(setData).catch(error => { if (error.name !== 'AbortError') setError(error.message.includes('404') ? 'Hero not found.' : 'Could not load this hero.') }); return () => controller.abort() }, [id, attempt])
  useEffect(() => { if (data) document.querySelector<HTMLElement>('h1')?.focus() }, [data])
  if (error) return <main><button className="back" onClick={() => navigate('/')}>← Hero library</button><ErrorState message={error} retry={retry} /></main>
  if (!data) return <main><LoadingState>Loading hero…</LoadingState></main>
  const { hero, skills } = data, passiveName = String(hero.passive.name ?? humanize(String(hero.passive.code ?? 'Passive unavailable'))), currentAcquisition = hero.acquisition.filter(source => source.current), historicalAcquisition = hero.acquisition.filter(source => !source.current), legacyAvailability = Object.values(hero.legacyAvailability ?? {}).filter(source => source.value !== null), supportedStats = Object.entries(hero.statSemantics ?? {}).filter(([, fact]) => fact.status !== 'unresolved' && fact.value !== null), unresolvedStats = Object.entries(hero.statSemantics ?? {}).filter(([, fact]) => fact.status === 'unresolved' && fact.value !== null)
  return <main><button className="back" onClick={() => navigate('/')}>← Hero library</button><section className="hero-head"><Portrait hero={hero} large /><div><span className="eyebrow">{hero.element ?? 'Unknown element'} {hero.class ?? 'Hero'}</span><h1 className="page-title" tabIndex={-1}>{hero.name}</h1><p>{hero.damageType ?? 'Unknown damage type'} · {humanize(hero.mobility ?? 'Unknown')}</p><p className="classification-label">Classification: {humanize(hero.classification)}{hero.classificationConfidence ? ` · ${hero.classificationConfidence} confidence` : ''}</p></div></section>
    <section className="profile"><Field label="Job (Class)" value={hero.class} /><Field label="Element" value={hero.element} /><Field label="Mobility" value={humanize(hero.mobility ?? 'Unknown')} /><Field label="Sex" value={hero.sex === 'f' ? 'Female' : hero.sex === 'm' ? 'Male' : 'Unknown'} /><Field label="Raw BaseStars" value={hero.progression.base_stars} title="Unresolved raw Heroes.csv design field; it is not presented as starting rarity or unlock rank." /><Field label="Supported evolution cap" value={hero.progression.max_stars} title="Strongly supported by the MaxStars field, the uniform playable-hero distribution, and 8-star evolution references; not treated as directly proven UI terminology." /><Field label="Rarity" value={hero.progression.rarity_name ?? hero.progression.rarity} /></section>
    <h2 className="section-title">Explicit medal acquisition</h2><section className="availability">{currentAcquisition.length ? currentAcquisition.map(source => <span className="available" key={source.id}>✓ {source.name}</span>) : <span className="unavailable">No current source found in extracted configuration</span>}</section>
    {historicalAcquisition.length > 0 && <><h2 className="section-title">Historical configuration sources</h2><section className="availability">{historicalAcquisition.map(source => <span className="unavailable" key={source.id}>{source.name}</span>)}</section></>}
    {legacyAvailability.length > 0 && <details className="legacy"><summary>Legacy availability indicators</summary><p>Raw Heroes.csv flags are retained as historical, unverified evidence and do not override explicit configuration.</p>{legacyAvailability.map(source => <div key={source.source_field}>{source.source_field}: {source.value ? 'enabled' : 'disabled'}</div>)}</details>}
    <h2 className="section-title">Passives / Attributes</h2><section className="skills traits">{hero.traits.length ? hero.traits.map(trait => <article key={trait.code}><span>Innate attribute</span><h3>{trait.name}</h3><p><FormattedText value={trait.description} hero={hero} /></p></article>) : <p className="state">No innate attributes found.</p>}</section>
    <h2 className="section-title">Base combat values</h2><section className="stats">{supportedStats.length ? supportedStats.map(([key, fact]) => <div key={key} title={`${fact.source_field} · ${humanize(fact.status)} · ${humanize(fact.unit)}`}><span>{fact.label}</span><strong>{formatStat(fact.value, fact.unit)}</strong></div>) : Object.entries(hero.stats).filter(([key, value]) => value !== null && !['power', 'base_stars', 'max_stars'].includes(key)).map(([key, value]) => <div key={key}><span>Raw {key.replaceAll('_', ' ')}</span><strong>{value}</strong></div>)}</section>
    {unresolvedStats.length > 0 && <details className="legacy"><summary>Unresolved source scores</summary><p>These raw design values are retained for traceability and are not presented as current gameplay totals.</p>{unresolvedStats.map(([key, fact]) => <div key={key}>{fact.label}: {String(fact.value)}</div>)}</details>}
    <h2 className="section-title">Spells / Ultimates</h2><section className="skills">{skills.length ? skills.map((skill, index) => <article key={skill.id}><span>{['First · Basic', 'Second · Special', 'Third · Ultimate'][index] ?? skill.type ?? 'Ability'}</span><h3>{skill.name || humanize(skill.id)}</h3><p><FormattedText value={skill.description} hero={hero} /></p>{skill.unresolvedPlaceholders?.length ? <small>Unresolved source placeholders: {skill.unresolvedPlaceholders.join(', ')}</small> : null}<div className="mechanics">{skillMechanics(skill).map(value => <small key={value}>{value}</small>)}</div>{skill.components.length > 0 && <details><summary>Source mechanics</summary>{skill.components.map((part, i) => <div className="source-part" key={`${part.kind}-${i}`}><b>{humanize(part.kind)}</b>{Object.entries(part.attributes).map(([key, value]) => <small key={key}>{humanize(key)}: {value}</small>)}</div>)}</details>}</article>) : <p className="state">No resolved skills available.</p>}
    {hero.passive.code && <article><span>Fourth ability (SP4) · Passive</span><h3>{passiveName}</h3><p>{hero.passive.description ?? `${hero.passive.target ? `Affects ${String(hero.passive.target).toLowerCase()}.` : ''} ${hero.passive.source_value != null ? `Source value: ${hero.passive.source_value}.` : ''}`}</p></article>}</section>
  </main>
}

function Field({ label, value, title }: { label: string; value: unknown; title?: string }) { return <div title={title}><span>{label}</span><strong>{String(value ?? '—')}</strong></div> }
function formatStat(value: string | number | null, unit: string) { return value == null ? '—' : unit === 'percent' ? `${value}%` : String(value) }
